// Seed data for bulk upload
// Note: coverImageUrl is now just the filename (slug.jpg)
// You need to manually upload images to Supabase Storage with these exact names
export const placesData = [
  // Lịch sử & Văn hóa
  {
    name: 'Dinh Độc Lập',
    description: 'Còn được biết đến là Dinh Thống Nhất, là một di tích lịch sử quan trọng của Việt Nam, nơi đánh dấu sự kết thúc của Chiến tranh Việt Nam.',
    addressText: '135 Nam Kỳ Khởi Nghĩa, Phường Bến Thành, Quận 1, TP. Hồ Chí Minh',
    district: 'Quận 1',
    latitude: 10.7769,
    longitude: 106.6954,
    coverImageUrl: 'dinh-doc-lap.jpg',
    openingHours: '08:00 – 16:30',
    priceInfo: '40.000 VNĐ (người lớn), 20.000 VNĐ (trẻ em)',
    tipsNotes: 'Nên đến vào buổi sáng để tránh đông người. Có hướng dẫn viên tiếng Anh.',
    isFeatured: true,
  },
  {
    name: 'Bảo tàng Chứng tích Chiến tranh',
    description: 'Bảo tàng trưng bày các hiện vật, tư liệu về Chiến tranh Việt Nam và những hậu quả của chiến tranh.',
    addressText: '28 Võ Văn Tần, Phường 6, Quận 3, TP. Hồ Chí Minh',
    district: 'Quận 3',
    latitude: 10.7797,
    longitude: 106.6919,
    coverImageUrl: 'bao-tang-chung-tich-chien-tranh.jpg',
    openingHours: '07:30 – 18:00',
    priceInfo: '40.000 VNĐ',
    tipsNotes: 'Cần thời gian khoảng 2-3 giờ để tham quan toàn bộ. Nội dung có thể gây ấn tượng mạnh.',
    isFeatured: true,
  },
  {
    name: 'Nhà thờ Đức Bà Sài Gòn',
    description: 'Công trình kiến trúc Gothic nổi tiếng, được xây dựng vào thế kỷ 19 bởi người Pháp.',
    addressText: '01 Công xã Paris, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    district: 'Quận 1',
    latitude: 10.7798,
    longitude: 106.6991,
    coverImageUrl: 'nha-tho-duc-ba-sai-gon.jpg',
    openingHours: '08:00 – 11:00, 15:00 – 16:00',
    priceInfo: 'Miễn phí',
    tipsNotes: 'Hiện đang được tu sửa. Chỉ có thể chụp hình bên ngoài.',
    isFeatured: true,
  },
  {
    name: 'Bưu điện Trung tâm Sài Gòn',
    description: 'Công trình kiến trúc đẹp mắt, được thiết kế bởi Gustave Eiffel, vẫn hoạt động như một bưu điện.',
    addressText: '02 Công xã Paris, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    district: 'Quận 1',
    latitude: 10.7799,
    longitude: 106.6999,
    coverImageUrl: 'buu-dien-trung-tam-sai-gon.jpg',
    openingHours: '07:00 – 19:00',
    priceInfo: 'Miễn phí',
    tipsNotes: 'Có thể mua bưu thiếp và tem để gửi từ đây.',
    isFeatured: true,
  },
  {
    name: 'Nhà hát Lớn Sài Gòn',
    description: 'Nhà hát opera với kiến trúc Pháp cổ điển, là địa điểm tổ chức các buổi biểu diễn nghệ thuật.',
    addressText: '07 Công Trường Lam Sơn, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    district: 'Quận 1',
    latitude: 10.7770,
    longitude: 106.7026,
    coverImageUrl: 'nha-hat-lon-sai-gon.jpg',
    openingHours: 'Tùy theo lịch biểu diễn',
    priceInfo: 'Tùy theo chương trình',
    tipsNotes: 'Nên đặt vé trước khi đến.',
    isFeatured: false,
  },
  {
    name: 'Chùa Ngọc Hoàng',
    description: 'Ngôi chùa Đạo giáo cổ kính với kiến trúc và trang trí đẹp mắt.',
    addressText: '73 Mai Thị Lựu, Phường Đa Kao, Quận 1, TP. Hồ Chí Minh',
    district: 'Quận 1',
    latitude: 10.7924,
    longitude: 106.6976,
    coverImageUrl: 'chua-ngoc-hoang.jpg',
    openingHours: '06:00 – 18:00',
    priceInfo: 'Miễn phí',
    tipsNotes: 'Ăn mặc lịch sự khi vào chùa.',
    isFeatured: false,
  },

  // Mua sắm
  {
    name: 'Chợ Bến Thành',
    description: 'Chợ nổi tiếng với đồ lưu niệm, quần áo, và ẩm thực địa phương.',
    addressText: 'Lê Lợi, Phường Bến Thành, Quận 1, TP. Hồ Chí Minh',
    district: 'Quận 1',
    latitude: 10.7720,
    longitude: 106.6981,
    coverImageUrl: 'cho-ben-thanh.jpg',
    openingHours: '06:00 – 18:00 (chợ ngày), 18:00 – 23:00 (chợ đêm)',
    priceInfo: 'Miễn phí vào cửa',
    tipsNotes: 'Hãy mặc cả khi mua sắm. Cẩn thận với tài sản cá nhân.',
    isFeatured: true,
  },
  {
    name: 'Chợ Lớn (Chợ Bình Tây)',
    description: 'Chợ lớn nhất khu vực Chợ Lớn với kiến trúc Trung Hoa đặc trưng.',
    addressText: '57A Thập Tự, Phường 2, Quận 6, TP. Hồ Chí Minh',
    district: 'Quận 6',
    latitude: 10.7474,
    longitude: 106.6499,
    coverImageUrl: 'cho-lon-cho-binh-tay.jpg',
    openingHours: '06:00 – 18:00',
    priceInfo: 'Miễn phí',
    tipsNotes: 'Đến sớm để tránh đông đúc.',
    isFeatured: false,
  },

  // Giải trí & Ăn uống
  {
    name: 'Phố đi bộ Nguyễn Huệ',
    description: 'Phố đi bộ sầm uất với nhiều sự kiện và hoạt động vui chơi.',
    addressText: 'Đường Nguyễn Huệ, Quận 1, TP. Hồ Chí Minh',
    district: 'Quận 1',
    latitude: 10.7742,
    longitude: 106.7040,
    coverImageUrl: 'pho-di-bo-nguyen-hue.jpg',
    openingHours: '24/7',
    priceInfo: 'Miễn phí',
    tipsNotes: 'Đẹp nhất vào buổi tối khi có đèn trang trí.',
    isFeatured: true,
  },
  {
    name: 'Phố Tây Bùi Viện',
    description: 'Khu vực sôi động về đêm với nhiều quán bar, nhà hàng quốc tế.',
    addressText: 'Đường Bùi Viện, Phường Phạm Ngũ Lão, Quận 1, TP. Hồ Chí Minh',
    district: 'Quận 1',
    latitude: 10.7673,
    longitude: 106.6927,
    coverImageUrl: 'pho-tay-bui-vien.jpg',
    openingHours: '24/7',
    priceInfo: 'Tùy theo địa điểm',
    tipsNotes: 'Sôi động nhất từ 20:00 đến 02:00.',
    isFeatured: false,
  },

  // Công viên & Thiên nhiên
  {
    name: 'Thảo Cầm Viên Sài Gòn',
    description: 'Sở thú và vườn thực vật lâu đời nhất Việt Nam.',
    addressText: '2B Nguyễn Bỉnh Khiêm, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    district: 'Quận 1',
    latitude: 10.7879,
    longitude: 106.7056,
    coverImageUrl: 'thao-cam-vien-sai-gon.jpg',
    openingHours: '07:00 – 18:00',
    priceInfo: '50.000 VNĐ (người lớn), 30.000 VNĐ (trẻ em)',
    tipsNotes: 'Thích hợp cho gia đình có trẻ nhỏ.',
    isFeatured: false,
  },

  // Tòa nhà cao tầng & Kiến trúc hiện đại
  {
    name: 'Tòa nhà Bitexco Financial Tower',
    description: 'Tòa nhà cao thứ 2 tại TP.HCM với đài quan sát Saigon Skydeck.',
    addressText: '36 Hồ Tùng Mậu, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    district: 'Quận 1',
    latitude: 10.7717,
    longitude: 106.7046,
    coverImageUrl: 'toa-nha-bitexco-financial-tower.jpg',
    openingHours: '09:30 – 21:30',
    priceInfo: '200.000 VNĐ',
    tipsNotes: 'Nên đến vào lúc hoàng hôn để ngắm cảnh đẹp.',
    isFeatured: true,
  },
  {
    name: 'Landmark 81',
    description: 'Tòa nhà cao nhất Việt Nam với trung tâm thương mại và đài quan sát.',
    addressText: '720A Đ. Điện Biên Phủ, Vinhomes Tân Cảng, Bình Thạnh, TP. Hồ Chí Minh',
    district: 'Bình Thạnh',
    latitude: 10.7946,
    longitude: 106.7218,
    coverImageUrl: 'landmark-81.jpg',
    openingHours: '08:30 – 21:30',
    priceInfo: 'Từ 250.000 VNĐ (đài quan sát)',
    tipsNotes: 'Mua vé trực tuyến để được giảm giá.',
    isFeatured: false,
  },

  // Khu vực thư giãn
  {
    name: 'Hồ Con Rùa',
    description: 'Công viên với hồ nước và đài phun nước, là nơi thư giãn của người dân địa phương.',
    addressText: 'Phường 6, Quận 3, TP. Hồ Chí Minh',
    district: 'Quận 3',
    latitude: 10.7826,
    longitude: 106.6934,
    coverImageUrl: 'ho-con-rua.jpg',
    openingHours: '24/7',
    priceInfo: 'Miễn phí',
    tipsNotes: 'Thích hợp để tập thể dục buổi sáng hoặc chiều.',
    isFeatured: false,
  },

  // Bảo tàng
  {
    name: 'Bảo tàng Mỹ thuật TP.HCM',
    description: 'Bảo tàng trưng bày các tác phẩm nghệ thuật Việt Nam từ cổ đại đến hiện đại.',
    addressText: '97A Phó Đức Chính, Phường Nguyễn Thái Bình, Quận 1, TP. Hồ Chí Minh',
    district: 'Quận 1',
    latitude: 10.7692,
    longitude: 106.6979,
    coverImageUrl: 'bao-tang-my-thuat-tphcm.jpg',
    openingHours: '08:00 – 17:00 (nghỉ thứ 2)',
    priceInfo: '30.000 VNĐ',
    tipsNotes: 'Có nhiều tác phẩm nghệ thuật truyền thống và đương đại.',
    isFeatured: false,
  },
  {
    name: 'Bảo tàng Lịch sử Việt Nam',
    description: 'Bảo tàng trưng bày các hiện vật về lịch sử Việt Nam từ thời tiền sử đến hiện đại.',
    addressText: '2 Nguyễn Bỉnh Khiêm, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    district: 'Quận 1',
    latitude: 10.7879,
    longitude: 106.7048,
    coverImageUrl: 'bao-tang-lich-su-viet-nam.jpg',
    openingHours: '08:00 – 17:00 (nghỉ thứ 2)',
    priceInfo: '30.000 VNĐ',
    tipsNotes: 'Thích hợp cho những ai quan tâm đến lịch sử.',
    isFeatured: false,
  },

  // Địa điểm khác
  {
    name: 'Tòa nhà Ủy ban Nhân dân TP.HCM',
    description: 'Tòa nhà chính quyền với kiến trúc Pháp đẹp mắt, được chiếu sáng vào ban đêm.',
    addressText: '86 Lê Thánh Tôn, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    district: 'Quận 1',
    latitude: 10.7765,
    longitude: 106.7009,
    coverImageUrl: 'toa-nha-uy-ban-nhan-dan-tphcm.jpg',
    openingHours: 'Chỉ xem bên ngoài',
    priceInfo: 'Miễn phí',
    tipsNotes: 'Đẹp nhất khi chụp ảnh vào ban đêm.',
    isFeatured: false,
  },
  {
    name: 'Chùa Bửu Long',
    description: 'Chùa Phật giáo với kiến trúc độc đáo, nổi tiếng với tượng Phật lớn.',
    addressText: '81 Nguyễn Xiển, Phường Long Bình, TP. Thủ Đức, TP. Hồ Chí Minh',
    district: 'TP. Thủ Đức',
    latitude: 10.8413,
    longitude: 106.7651,
    coverImageUrl: 'chua-buu-long.jpg',
    openingHours: '06:00 – 18:00',
    priceInfo: 'Miễn phí',
    tipsNotes: 'Cần đi xe khoảng 30-40 phút từ trung tâm thành phố.',
    isFeatured: false,
  },

  // Ngoại ô
  {
    name: 'Địa đạo Củ Chi',
    description: 'Hệ thống địa đạo lịch sử từ thời chiến tranh Việt Nam.',
    addressText: 'Phú Hiệp, Củ Chi, TP. Hồ Chí Minh',
    district: 'Củ Chi',
    latitude: 11.0510,
    longitude: 106.4946,
    coverImageUrl: 'dia-dao-cu-chi.jpg',
    openingHours: '07:00 – 17:00',
    priceInfo: '110.000 VNĐ',
    tipsNotes: 'Nên đặt tour từ trung tâm thành phố. Cần khoảng nửa ngày để tham quan.',
    isFeatured: false,
  },
  {
    name: 'Công viên Văn hóa Suối Tiên',
    description: 'Công viên giải trí lớn với nhiều trò chơi và khu vực nước.',
    addressText: 'Đường Hà Nội, Phường Phước Long B, TP. Thủ Đức, TP. Hồ Chí Minh',
    district: 'TP. Thủ Đức',
    latitude: 10.8704,
    longitude: 106.7984,
    coverImageUrl: 'cong-vien-van-hoa-suoi-tien.jpg',
    openingHours: '08:00 – 18:00',
    priceInfo: 'Từ 100.000 VNĐ',
    tipsNotes: 'Thích hợp cho gia đình. Nên đến vào ngày trong tuần để tránh đông.',
    isFeatured: false,
  },
];
